
# Server
server.port=3000
server.address=0.0.0.0

# Database
spring.datasource.url=jdbc:sqlite:data/pnrs_database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.com.pnrstools=DEBUG
logging.level.org.springframework.web=INFO

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# IP Whitelist
security.allowed-ips=127.0.0.1,::1,::ffff:127.0.0.1

# Endpoints (sobreescribir con variables de entorno)
mock.int.url=http://internal-OCIAME2IDLB00001-1637202973.eu-west-1.elb.amazonaws.com:8087/disruption/mocks/order/create
mock.pre.url=http://internal-OCIAME2IDLB00001-339266582.eu-west-1.elb.amazonaws.com:8087/disruption/mocks/order/create
soap.disruption.url=https://reacomapppre.w-sdlc-pre-cc-pss.aws.iberia.es:1992/Reaccom/Reaccom_Disruption_Services
soap.action=http://Reaccom_Admin.svc/IReaccom_Disruption_Services/DisruptionIB

# NDC
auth.url=${AUTH_URL:}
auth.basic.credentials=${AUTH_BASIC_CREDENTIALS:}
auth2.header=${AUTH2_HEADER:Basic DC_exit/kOGBOp864E0DQmbz.uJU}
app.version=${APP_VERSION:200}
host.url=${HOST_URL:}
host.url.orm=${HOST_URL_ORM:}
cookie.string=${COOKIE_STRING:mt.v=2.1037978947.1778589064559; _cq_duid=1.1778589064.c1uj7YORL5CzwQI4; _fbp=fb.1.1778589066107.20468017513695995; _ga=GA1.1.1612261184.1778589066; _twpid=tw.1778589066156.259429965760051712; QuantumMetricUserID=68abaadafa44b1f77eb30e0a25352d0a; rskxRunCookie=0; rCookie=frnw2tsavorzyk2bv9g388mpf874we; OptanonAlertBoxClosed=2026-05-21T09:54:25.791Z; _gcl_gs=2.1.k1$i1779869426$u168300281; _gcl_aw=GCL.1779869429.EAIaIQobChMI9OLmkoLZlAMVSZpoCR0wNwFwEAMYASAAEgKXgPD_BwE; OptanonConsent=isGpcEnabled=0&datestamp=Wed+May+27+2026+11%3A15%3A54+GMT%2B0200+(hora+de+verano+de+Europa+central)&version=202212.1.0&isIABGlobal=false&hosts=&consentId=c4f4ee9d-0c67-427c-be29-c628e8de2afb&interactionCount=1&landingPath=NotLandingPage&groups=C0001%3A1%2CC0002%3A1%2CC0005%3A1%2CC0004%3A1%2CC0003%3A1&geolocation=ES%3BCT&AwaitingReconsent=false;}

# Local IP
local.ip=${LOCAL_IP:localhost}
